name: ci

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: jamesari/backend:latest
          platforms: linux/amd64,linux/arm64
      -
        name: Build and push loadbalancer image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:loadbalancer"
          push: true
          tags: jamesari/loadbalancer:latest
          platforms: linux/amd64,linux/arm64
