name: ci

on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: JamesAri/dce-sp:latest
    #   -
    #     name: Build and push loadbalancer image
    #     uses: docker/build-push-action@v6
    #     with:
    #       context: "{{defaultContext}}:loadbalancer"
    #       push: true
    #       tags: user/app:latest
